server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
developer:
  name: "Santhosh"
  email: "santhosh.don@rediffmail.com"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #for circuit-breaker endpoints
  health:
    circuitbreakers:
      enabled: true
    show-details: always
  tracing:
    sampling:
      probability: 1.0
#Circuit breaker configurations
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG
  
