server:
  port: 8085
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/employee_db'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: 'http://localhost:8761/eureka/'
developer:
  name: Santhosh
  email: santhosh.don@rediffmail.com

#Resilience 4j configuration is in application.yaml
        
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG
