server:
  port: 8085
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/employee_db'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: 'http://localhost:8761/eureka/'
developer:
  name: Santhosh
  email: santhosh.don@rediffmail.com


resilience4j:
  circuitbreaker:
    instances:
      exampleClient:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 2
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    resilience4j:
      enabled: true
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG
